version: "3"

services:
  # BACKEND_GATEWAY
  backend_gateway:
    container_name: backend_gateway
    image: backend_gateway_alpine
    privileged: true
    network_mode: host
    volumes:
      - /tmp:/tmp:z
    deploy:
      resources:
        limits:
          cpus: '2.0'       # Limit to 50% of one CPU core
          memory: 512M      # Limit to 512 megabytes of memory
        reservations:
          cpus: '0.5'       # Reserve 20% of one CPU core
          memory: 256M      # Reserve 256 megabytes of memory
  # MQTT_GATEWAY
  mqtt_gateway:
    container_name: mqtt_gateway
    image: mqtt_gateway
    privileged: true
    network_mode: host
    volumes:
      - /tmp:/tmp:z
    deploy:
      resources:
        limits:
          cpus: '1.0'       # Limit to 50% of one CPU core
          memory: 512M      # Limit to 512 megabytes of memory
        reservations:
          cpus: '0.2'       # Reserve 20% of one CPU core
          memory: 256M      # Reserve 256 megabytes of memory
  # ECUS_GATEWAY
  ECUs_gateway:
    container_name: ECUs_gateway
    image: udp_server_alpine
    network_mode: host
    privileged: true
    volumes:
      - /tmp:/tmp:z
    deploy:
      resources:
        limits:
          cpus: '0.5'       # Limit to 50% of one CPU core
          memory: 512M      # Limit to 512 megabytes of memory
        reservations:
          cpus: '0.2'       # Reserve 20% of one CPU core
          memory: 256M      # Reserve 256 megabytes of memory
  # GPS_TRANSCEIVER
  gps_transceiver:
    container_name: gps_transceiver
    image: gps-serial-receiver
    privileged: true
    network_mode: host
    volumes:
      - /tmp:/tmp:z
      - /dev/ttyACM0:/dev/ttyACM0
    deploy:
      resources:
        limits:
          cpus: '0.5'       # Limit to 50% of one CPU core
          memory: 512M      # Limit to 512 megabytes of memory
        reservations:
          cpus: '0.2'       # Reserve 20% of one CPU core
          memory: 256M      # Reserve 256 megabytes of memory
