version: "2"

services:
  # BACKEND_GATEWAY
  backend_gateway:
    container_name: backend_gateway
    image: registry.digitalocean.com/vehicle-plus/tcu_backend-gateway:v2
    privileged: true
    network_mode: host
    volumes:
      - /tmp:/tmp:z
    deploy:
      resources:
        limits:
          cpus: '2.0'       # Limit to 50% of one CPU core
          memory: 512M      # Limit to 512 megabytes of memory
        reservations:
          cpus: '0.5'       # Reserve 20% of one CPU core
          memory: 256M      # Reserve 256 megabytes of memory
  # MQTT_GATEWAY
  mqtt_gateway:
    container_name: mqtt_gateway
    image: registry.digitalocean.com/vehicle-plus/tcu_mqtt-gateway:v0
    privileged: true
    network_mode: host
    volumes:
      - /tmp:/tmp:z
    deploy:
      resources:
        limits:
          cpus: '1.0'       # Limit to 50% of one CPU core
          memory: 512M      # Limit to 512 megabytes of memory
        reservations:
          cpus: '0.2'       # Reserve 20% of one CPU core
          memory: 256M      # Reserve 256 megabytes of memory
  # ECUS_GATEWAY
  ecus_ethernet_gateway:
    container_name: ecus_ethernet_gateway
    image: registry.digitalocean.com/vehicle-plus/tcu_ecu-ethernet-gateway:v5
    network_mode: host
    privileged: true
    volumes:
      - /tmp:/tmp:z
    deploy:
      resources:
        limits:
          cpus: '0.5'       # Limit to 50% of one CPU core
          memory: 512M      # Limit to 512 megabytes of memory
        reservations:
          cpus: '0.2'       # Reserve 20% of one CPU core
          memory: 256M      # Reserve 256 megabytes of memory
  # GPS_TRANSCEIVER
  gps_transceiver:
    container_name: gps_transceiver
    image: registry.digitalocean.com/vehicle-plus/tcu_gps-serial-receiver:v0
    privileged: true
    network_mode: host
    volumes:
      - /tmp:/tmp:z
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/gps_serial:/dev/gps_serial
    deploy:
      resources:
        limits:
          cpus: '0.5'       # Limit to 50% of one CPU core
          memory: 512M      # Limit to 512 megabytes of memory
        reservations:
          cpus: '0.2'       # Reserve 20% of one CPU core
          memory: 256M      # Reserve 256 megabytes of memory
 # portainer
  portainer:
    image: portainer/portainer-ce:linux-arm64-2.18.4-alpine
    ports:
      - 9443:9443
    volumes:
        - data:/data
        - /var/run/docker.sock:/var/run/docker.sock
volumes:
  data:
